spring:
    application:
        name: formula-grid

    data:
        mongodb:
            uri: mongodb://localhost:27017/formula-grid

server:
    port: 5900

logging:
    level:
        com.formulagrid: DEBUG
        org.springframework: DEBUG

f1:
    joplica-api:
        base-url: https://api.jolpi.ca/ergast/f1/
        timeout: 10000
